[package]
name = "open-and-wait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
bytes = "1.2.1"
etherparse = "0.12.0"
mqttbytes = "0.6.0"
rumqttc = "0.17.0"
